version: "3.9"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test-admin:/app
      - react-admin-node-modules:/app/node_modules
    ports:
      - 5173:5173
volumes:
  react-admin-node-modules:
